version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-client
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: board-app      
    volumes:
      - ./postgres:/var/lib/postgresql/data

    ports:
      - 3001:5432

  adminer:
    image: adminer
    restart: always
    container_name: postgres-admin
    ports:
      - 3002:8080